pankajblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#admin.autodiscover()
app_name = 'pblog'

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pblog/', include('pblog.urls',namespace='pblog')),  
   
]

pblog/urls.py
from django.conf.urls import include
from django.conf.urls import url
from pblog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
   
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^post/$', views.add_new_post, name='post'),
    url(r'^postdetail/(?P<post_id>[0-9])$', views.post_detail, name='post_detail'),
]

pblog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    user_id = models.IntegerField(max_length=10)
    title = models.TextField()
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0,max_length=2)

pblog/controller.py
from .models import Post
from django.contrib import auth

class Post_detail():
  
    def shrot_description_post(self):
        list1 = []
        tempdata = Post.objects.raw(""" select p.*,au.username from pblog_post as p join auth_user as au
                                    on p.user_id = au.id where p.status = 1 order by p.id desc""")
        for i in tempdata:
            tempdict = {}
            short = i.message
            if len(short) > 230:
                 msg =  short[:250]
                 msg = msg + ' ...'
                
            else: 
                msg = short
           
            tempdict['title'] = i.title
            tempdict['message'] = msg
            tempdict['date'] = i.date
            tempdict['post_id'] = i.id
            tempdict['username'] = i.username
            list1.append(tempdict)
        
        return list1
    
    def single_post_detail(self,post_id):
        data = Post.objects.raw(""" select p.*,au.username from pblog_post as p join auth_user as au
                                    on p.user_id = au.id where p.status = 1 and  p.id = %s """%post_id)
        return data

pblog/views.py
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from models import Post
from controller import Post_detail
p = Post_detail()
from django.contrib.auth.decorators import login_required


# Create your views here.

def registration(request):
 
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/pblog/login')
    else:
        form = UserCreationForm()
    return render(request,'pblog/registration.html',{'form':form})



def user_login(request):
    msg = ''
    username = password = ''
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect('/pblog')
    else:
        msg = "Dose not match user name and password"
    return render(request,'pblog/login.html',{'msg':msg})


def user_logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/pblog')


def index(request):
    ######################
    postdata = p.shrot_description_post()
    ######################
    return render(request,'pblog/index.html',{'postdata':postdata})

def add_new_post(request):
    name =  request.user.username
  
    userid = request.user.id
    
    if request.method == 'POST':
        #print request.POST
        title = request.POST['title']
        msg = request.POST['content']
        p = Post(user_id=userid,title=title,message=msg)
        p.save()
        return HttpResponseRedirect('/pblog')
    return render(request, 'pblog/newpost.html')

def post_detail(request,post_id):
    postdata = p.single_post_detail(post_id)
    return render(request,'pblog/post_detail.html',{'postdata':postdata})

pblog/templates/pblog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Write Your Words</title>

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
        <script src="{% static 'js/jquery.js' %}"></script>

        <!-- Custom Fonts -->
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <body>

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--                <a class="navbar-brand" href="index.html"></a>-->
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url 'pblog:index' %}">Home</a>
                        </li>
                        <li>
                            <a href="about.html">About</a>
                        </li>
                        <li>
                            <a href="{% url 'pblog:post' %}">Add Post</a>
                        </li>
                        {% if user.is_authenticated %}
                       
                        <li> 

                            <a href="/pblog/logout">Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="/pblog/login">Login</a>
                        </li>
                        {% endif %}
                        <li>
                            <!--                        <a href="registration/">Registration</a>-->
                            <a href="{% url 'pblog:registration' %}">Registration</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- Page Header -->
        {% block content %}

        {% endblock %}



        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- jQuery -->


        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{% static 'js/clean-blog.min.js' %}"></script>


    </body>

</html>

pblog/templates/pblog/index.html
{% extends 'pblog/base.html' %}
  {% block content %}
     {% load staticfiles %}
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static "img/home-bg.jpg" %}) ">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Express Yourself</h1>
<!--                        <hr class="small">
                        <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>-->
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              {% if postdata %}  
               {% for i in postdata %}
                <div class="post-preview">
                    <a href="#">
                        <h4 class="post-title">
                            {{ i.title | capfirst}}
                        </h4>
                        <h4 class="post-subtitle">
                          {{ i.message | safe }}
                       </h4>
                    </a>
                    <span class="post-meta">Posted by <a href="#">{{i.username}}</a> on {{i.date}}  </span>
                    <span class="pull-right"><a href="{% url 'pblog:post_detail' i.post_id %}" class="">Read More</a></span>
                </div>
                <hr>
             {% endfor %}
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
                {% else %}
                <center><h2>No Post Available</h2></center>
                 {% endif %}
            </div>
        </div>
    </div>

    <hr>

  {% endblock %}

pblog/templates/pblog/login.html
{% extends 'pblog/base.html' %}
 {% load staticfiles %}
  {% block content %}
    
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->

        <header class="intro-header" style="background-image: url({% static "img/contact-bg.jpg" %}) ">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Login From Here</h1>
<!--                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>-->
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Please Fill Fields For Login</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form method='post'>{% csrf_token %}
                    
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>UserName</label>
                            <input type="text" class="form-control" placeholder="UserName" id="name" name='username' required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Password</label>
                            <input type="password" class="form-control" placeholder="Password" id="email" name='password' required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                      <br>
                 
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit"  class="btn btn-default">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>

  {% endblock %}

pblog/templates/pblog/newpost.html
{% extends 'pblog/base.html' %}
{% block content %}
{% load staticfiles %}
<script src="{% static 'tinymce/tinymce.min.js'  %}"></script>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static "img/about-bg.jpg" %}) ">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Add New Post</h1>
<!--                        <hr class="small">
                        <span class="subheading">This is what I do.</span>-->
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                
                
                  <form method='post'> {% csrf_token %}
                <div class='form-group'>

                    <div class = "form-group">
                        <label for = "name">Title</label>
                        <input type = "text" name='title' class = "form-control" required>
                    </div>
                    <div class = "form-group">
                        <label for = "name">Content</label>
                        <textarea name='content'></textarea>
                    </div>
                   <div class = "form-group">
                       {% if user.is_authenticated %}
                       <button type='submit' name='submit' class='btn btn-default'>Submit</button>
                    {% else %}
                     <button type='submit' name='submit' class='btn btn-default' disabled>Submit</button>

                     {% endif %}
                   </div>

                </div>
               </form>
         
            </div>
        </div>
    </div>

<script>
    $(function () {
        tinymce.init({
            selector: 'textarea',
            height: 350,
            theme: 'modern',
            plugins: [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools'
            ],
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons',
            image_advtab: true,
            templates: [
                {title: 'Test template 1', content: 'Test 1'},
                {title: 'Test template 2', content: 'Test 2'}
            ],
            content_css: [
                '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
                '//www.tinymce.com/css/codepen.min.css'
            ]
        });
    });
</script>
{% endblock %}

pblog/templates/pblog/post_detail.html
{% extends 'pblog/base.html' %}
  {% block content %}
     {% load staticfiles %}
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static "img/home-bg.jpg" %}) ">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Express Yourself</h1>
<!--                        <hr class="small">
                        <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>-->
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
               {% for i in postdata %}
                <div class="post-preview">
                    <a href="#">
                        <h4 class="post-title">
                           {{ i.title | capfirst}}
                        </h4>
                        <h4 class="post-subtitle">
                          {{ i.message | safe }}
                       </h4>
                    </a>
                    <span class="post-meta">Posted by <a href="#">{{i.username}}</a> on {{i.date}}  </span>
                </div>
                
             {% endfor %}
                <!-- Pager -->
                
            </div>
        </div>
    </div>

    <hr>

  {% endblock %}

pblog/templates/pblog/registration.html
{% extends 'pblog/base.html' %}
{% load staticfiles %}
{% block content %}

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->

<header class="intro-header" style="background-image: url({% static "img/contact-bg.jpg" %}) ">
        <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>Registartion</h1>
                    <!--                    <hr class="small">
                                        <span class="subheading">Have questions? I have answers (maybe).</span>-->
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p> Please Fill Fields For Login</p>
            <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
            <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
            <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
            <form method='post'>{% csrf_token %}

                {% for field in form %}
                <div class="row control-group">
                    <div class="form-group col-xs-12 ">
                        <!-- Render the field label tag -->
                        <span> {{ field.label_tag }}</span>
                        <!-- If the field is required, display a * next to the field label -->
                        {% if field.field.required %}
                        *
                        {% endif %}
                        <br/>
                        <!-- Render the input field -->
                        <span> {{ field }}</span>
                        <!-- Iterate over the field's errors, if any and display
                 them one by one in a error alert
                        -->
                        {% if field.errors %}
                        <p class="error">
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </p>
                        {% endif %}
                    </div>
                </div>
                <hr>
                {% endfor %}
                <br>  
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<hr>
<script>
    $(function(){
       $("input").css({"width":"50%","border":"1px solid #D0D0D0 "});
    });
</script>

{% endblock %}